### ISSUE TITLE
Conflict in python version

### ISSUE THREAD

**Issue by chrisdotm** [pawadski/curlhttp_exporter#6]
There seems to be a conflict between the wanted python version here. Dockerfile is using a base image for python 3.8 while the script attempts to use python 3.6

https://github.com/pawadski/curlhttp_exporter/blob/1c1a2f15229798319ec0c84a6335f360187bf840/Dockerfile#L1
https://github.com/pawadski/curlhttp_exporter/blob/1c1a2f15229798319ec0c84a6335f360187bf840/exporter.py#L1

**Comment by pawadski** [comment]
Thank you for pointing this out. The Docker image will still run it through the installed Python 3 version but I should fix this anyway!

**Comment by pawadski** [comment]
I believe I've "corrected" this to use `python3` in the latest commit.
